-- MySQL Script generated by MySQL Workbench
-- Fri May  8 12:50:12 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema seisabd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema seisabd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `seisabd` DEFAULT CHARACTER SET utf8 ;
USE `seisabd` ;

-- -----------------------------------------------------
-- Table `seisabd`.`nivel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seisabd`.`nivel` (
  `id` INT NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `seisabd`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seisabd`.`empleado` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `mesa` INT NOT NULL,
  `cuarto` VARCHAR(45) NOT NULL,
  `turno` VARCHAR(45) NOT NULL,
  `nivel_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_empleado_table11_idx` (`nivel_id` ASC) ,
  CONSTRAINT `fk_empleado_table11`
    FOREIGN KEY (`nivel_id`)
    REFERENCES `seisabd`.`nivel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `seisabd`.`certificaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seisabd`.`certificaciones` (
  `id` INT NOT NULL,
  `modelo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `seisabd`.`modelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seisabd`.`modelo` (
  `id` INT NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `cpn` VARCHAR(45) NOT NULL,
  `familia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `seisabd`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seisabd`.`producto` (
  `lote_externo` VARCHAR(15) NOT NULL,
  `TWO` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `P.O.` VARCHAR(45) NOT NULL,
  `modelo_id` INT NOT NULL,
  PRIMARY KEY (`lote_externo`),
  INDEX `fk_producto_modelo1_idx` (`modelo_id` ASC) ,
  CONSTRAINT `fk_producto_modelo1`
    FOREIGN KEY (`modelo_id`)
    REFERENCES `seisabd`.`modelo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `seisabd`.`proceso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seisabd`.`proceso` (
  `id` VARCHAR(45) NOT NULL,
  `producto_lote_externo` VARCHAR(15) NOT NULL,
  `fecha` VARCHAR(45) NOT NULL,
  `hora` VARCHAR(45) NOT NULL,
  `duracion` VARCHAR(45) NOT NULL,
  `empleado_id` INT NOT NULL,
  INDEX `fk_producto_has_operador_producto1_idx` (`producto_lote_externo` ASC) ,
  PRIMARY KEY (`id`),
  INDEX `fk_proceso_empleado1_idx` (`empleado_id` ASC) ,
  CONSTRAINT `fk_producto_has_operador_producto1`
    FOREIGN KEY (`producto_lote_externo`)
    REFERENCES `seisabd`.`producto` (`lote_externo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proceso_empleado1`
    FOREIGN KEY (`empleado_id`)
    REFERENCES `seisabd`.`empleado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `seisabd`.`inspeccion_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seisabd`.`inspeccion_producto` (
  `id` INT NOT NULL,
  `producto_lote_externo` VARCHAR(15) NOT NULL,
  `empleado_id` INT NOT NULL,
  `# revision` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `hora` TIME NOT NULL,
  INDEX `fk_inspeccion_has_producto_producto1_idx` USING BTREE (`producto_lote_externo`) ,
  PRIMARY KEY (`id`),
  INDEX `fk_inspeccion_producto_empleado1_idx` (`empleado_id` ASC) ,
  CONSTRAINT `fk_inspeccion_has_producto_producto1`
    FOREIGN KEY (`producto_lote_externo`)
    REFERENCES `seisabd`.`producto` (`lote_externo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inspeccion_producto_empleado1`
    FOREIGN KEY (`empleado_id`)
    REFERENCES `seisabd`.`empleado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `seisabd`.`sutura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seisabd`.`sutura` (
  `id` INT NOT NULL,
  `cpn` VARCHAR(45) NOT NULL,
  `lote` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `seisabd`.`sutura_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seisabd`.`sutura_producto` (
  `id` INT NOT NULL,
  `producto_lote_externo` VARCHAR(15) NOT NULL,
  `sutura_id` INT NOT NULL,
  `fecha` DATE NOT NULL,
  INDEX `fk_producto_has_sutura_sutura1_idx` (`sutura_id` ASC) ,
  INDEX `fk_producto_has_sutura_producto1_idx` (`producto_lote_externo` ASC) ,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_producto_has_sutura_producto1`
    FOREIGN KEY (`producto_lote_externo`)
    REFERENCES `seisabd`.`producto` (`lote_externo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_has_sutura_sutura1`
    FOREIGN KEY (`sutura_id`)
    REFERENCES `seisabd`.`sutura` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `seisabd`.`sutura_liberada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seisabd`.`sutura_liberada` (
  `id` VARCHAR(45) NOT NULL,
  `sutura_id` INT NOT NULL,
  `empleado_id` INT NOT NULL,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_inspector_has_sutura_sutura1_idx` (`sutura_id` ASC) ,
  INDEX `fk_sutura liberada_empleado1_idx` (`empleado_id` ASC) ,
  CONSTRAINT `fk_inspector_has_sutura_sutura1`
    FOREIGN KEY (`sutura_id`)
    REFERENCES `seisabd`.`sutura` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sutura liberada_empleado1`
    FOREIGN KEY (`empleado_id`)
    REFERENCES `seisabd`.`empleado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `seisabd`.`defecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seisabd`.`defecto` (
  `id` INT NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `dispocision` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `seisabd`.`herramienta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seisabd`.`herramienta` (
  `id` INT NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `seisabd`.`herramienta_has_empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seisabd`.`herramienta_has_empleado` (
  `id` INT NOT NULL,
  `herramienta_id` INT NOT NULL,
  `empleado_id` INT NOT NULL,
  `valor` VARCHAR(45) NULL,
  INDEX `fk_herramienta_has_empleado_empleado1_idx` (`empleado_id` ASC) ,
  INDEX `fk_herramienta_has_empleado_herramienta1_idx` (`herramienta_id` ASC) ,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_herramienta_has_empleado_herramienta1`
    FOREIGN KEY (`herramienta_id`)
    REFERENCES `seisabd`.`herramienta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_herramienta_has_empleado_empleado1`
    FOREIGN KEY (`empleado_id`)
    REFERENCES `seisabd`.`empleado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `seisabd`.`empleado_certificaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seisabd`.`empleado_certificaciones` (
  `id` VARCHAR(45) NOT NULL,
  `empleado_id` INT NOT NULL,
  `certificaciones_id` INT NOT NULL,
  `fecha` DATE NULL,
  INDEX `fk_empleado_has_certificaciones_certificaciones1_idx` (`certificaciones_id` ASC) ,
  INDEX `fk_empleado_has_certificaciones_empleado1_idx` (`empleado_id` ASC) ,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_empleado_has_certificaciones_empleado1`
    FOREIGN KEY (`empleado_id`)
    REFERENCES `seisabd`.`empleado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empleado_has_certificaciones_certificaciones1`
    FOREIGN KEY (`certificaciones_id`)
    REFERENCES `seisabd`.`certificaciones` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `seisabd`.`supervision`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seisabd`.`supervision` (
  `id` INT NOT NULL,
  `supervisado` INT NOT NULL,
  `supervisa` INT NOT NULL,
  INDEX `fk_empleado_has_empleado_empleado2_idx` (`supervisa` ASC) ,
  INDEX `fk_empleado_has_empleado_empleado1_idx` (`supervisado` ASC) ,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_empleado_has_empleado_empleado1`
    FOREIGN KEY (`supervisado`)
    REFERENCES `seisabd`.`empleado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empleado_has_empleado_empleado2`
    FOREIGN KEY (`supervisa`)
    REFERENCES `seisabd`.`empleado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `seisabd`.`inspecciondDefectos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seisabd`.`inspecciondDefectos` (
  `inspeccion_producto_id` INT NOT NULL,
  `defecto_id` INT NOT NULL,
  INDEX `fk_inspeccion_producto_has_defecto_defecto1_idx` (`defecto_id` ASC) ,
  INDEX `fk_inspeccion_producto_has_defecto_inspeccion_producto1_idx` (`inspeccion_producto_id` ASC) ,
  CONSTRAINT `fk_inspeccion_producto_has_defecto_inspeccion_producto1`
    FOREIGN KEY (`inspeccion_producto_id`)
    REFERENCES `seisabd`.`inspeccion_producto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inspeccion_producto_defecto1`
    FOREIGN KEY (`defecto_id`)
    REFERENCES `seisabd`.`defecto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `seisabd`.`rechazo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seisabd`.`rechazo` (
  `producto_lote_externo` VARCHAR(15) NOT NULL,
  `id` INT NOT NULL,
  `ncr` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_rechazo_producto1`
    FOREIGN KEY (`producto_lote_externo`)
    REFERENCES `seisabd`.`producto` (`lote_externo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `seisabd`.`embarcado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seisabd`.`embarcado` (
  `producto_lote_externo` VARCHAR(15) NOT NULL,
  `id` INT NOT NULL,
  `bin` VARCHAR(45) NULL,
  `packingList` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_embarcado_producto1`
    FOREIGN KEY (`producto_lote_externo`)
    REFERENCES `seisabd`.`producto` (`lote_externo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `seisabd`.`aceptado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seisabd`.`aceptado` (
  `id` INT NOT NULL,
  `fecha` DATE NULL,
  `hora` TIME NULL,
  `producto_lote_externo` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_aceptado_producto1_idx` (`producto_lote_externo` ASC) ,
  CONSTRAINT `fk_aceptado_producto1`
    FOREIGN KEY (`producto_lote_externo`)
    REFERENCES `seisabd`.`producto` (`lote_externo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
